// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Generates the BuildConfig object that every SFC module logs on start-up.
 *
 * The previous in-script version ran `copy { }` from the task's *configuration* action, so it wrote
 * into src/main/kotlin on every Gradle invocation while the registered task itself declared no
 * actions, inputs or outputs - meaning compileKotlin had no dependency on whatever produced the
 * file it compiled.
 */
abstract class GenerateBuildConfig : DefaultTask() {

    /**
     * Package the object is declared in. Nothing in the tree imports BuildConfig by name, so this
     * must equal the package of the class that reads it, or resolution fails to compile.
     */
    @get:Input
    abstract val packageName: Property<String>

    /** VERSION for adapters, targets and metrics; MODULE_VERSION for core/sfc-main and core/sfc-uberjar. */
    @get:Input
    abstract val versionConstant: Property<String>

    @get:Input
    abstract val moduleVersion: Property<String>

    @get:Input
    abstract val coreVersion: Property<String>

    @get:Input
    abstract val ipcVersion: Property<String>

    /** Extra NAME=value pairs appended to the toString() line; only adapters/modbus-tcp uses it. */
    @get:Input
    abstract val extraVersions: MapProperty<String, String>

    @get:Input
    abstract val moduleLabel: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val pkg = packageName.get()
        val constant = versionConstant.get()
        val extras = extraVersions.get().entries.joinToString("") { ", ${it.key}=${it.value}" }

        val root = outputDir.get().asFile
        // Wiped rather than overwritten so that renaming packageName cannot leave a second
        // BuildConfig behind, which would fail the build with a duplicate JVM class declaration.
        root.deleteRecursively()
        val packageDir = root.resolve(pkg.replace('.', '/'))
        packageDir.mkdirs()
        packageDir.resolve("BuildConfig.kt").writeText(
            """
              |// Generated by the generateBuildConfig task. Do not edit.
              |package $pkg
              |
              |object BuildConfig {
              |  const val CORE_VERSION = "${coreVersion.get()}"
              |  const val IPC_VERSION = "${ipcVersion.get()}"
              |  const val $constant = "${moduleVersion.get()}"
              |    override fun toString() = "SFC_MODULE ${moduleLabel.get()}: VERSION=${'$'}$constant$extras, SFC_CORE_VERSION=${'$'}CORE_VERSION, SFC_IPC_VERSION=${'$'}IPC_VERSION"
              |}
              |
            """.trimMargin()
        )
    }
}
